- id: DS001
  file: from.rego
- id: DS002
  file: user.rego
- id: DS003
  file: apt_cache.rego
- id: DS004
  file: port22.rego
- id: DS005
  file: add_instead_of_copy.rego
- id: DS006
  file: run_using_apt_upgrade.rego
- id: DS007
  file: copy_from_references_current_from_alias.rego
- id: DS008
  file: yum_update_disabled.rego
- id: DS009
  file: multiple_entrypoint_instructions_listed.rego
- id: DS010
  file: unix_ports_out_of_range.rego








