---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    spec:
      hostIPC: true
      hostAliases:
      - ip: "127.0.0.1"
        hostname: ["foo.bar"]
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: carts-db
        image: mongo:latest
        securityContext:
          runAsNonRoot: false
          capabilities:
            drop: ["NET_ADMIN", "SYS_TIME"]
        resources:
          limits:
            memory: 24m
      - name: app
        image: app
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            memory: 24m
      initContainers:
      - name: carts-init
        image: mongo:1.28
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: 24M
