---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: carts-db
        image: mongo
        securityContext:
          runAsNonRoot: false
        resources:
          limits:
            memory: 24m
      - name: app
        image: app
        securityContext:
          allowPrivilegeEscalation: true
        resources:
          limits:
            memory: 24m
      initContainers:
      - name: carts-init
        image: mongo
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            memory: 24M
